# **Naive Bays**

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'E:\BDA\machine_learning\Ml_datasets\play_tennis.csv')
data.head()
data.drop('day', axis=1, inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

# Problem 1

#?Outlook = sunny, Temprature = hot, Humidity = high, Windy = weak
#? play or not play

#! Splution
#! p(yes / Sunny, hot, high, weak) = p(Sunny / yes) * p(hot / yes) * p(high / yes) * p(weak / yes) * p(yes)

#! p(no / Sunny, hot, high, weak) = p(Sunny / no) * p(hot / no) * p(high / no) * p(weak / no) * p(no)

#? compare and decide which one is greater and predict accordingly

## Traning 
- **in traning phase naive bays create a look up table in a dictionery formate in which it contains all the possible output  probabilitys**

In [4]:
data["play"].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
py = 9/14
pn = 5/14

In [6]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [7]:
# Outlook 
pd.crosstab(data["outlook"], data["play"], margins=True)

play      No  Yes  All
outlook
Overcast   0    4    4
Rain       2    3    5
Sunny      3    2    5
All        5    9   14

In [10]:
Pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [9]:
# Temperature
pd.crosstab(data["temp"], data["play"], margins=True)

play  No  Yes  All
temp
Cool   1    3    4
Hot    2    2    4
Mild   2    4    6
All    5    9   14

In [11]:
pcoolno = 1/5
photno = 2/5
pmildno = 2/5

pcoolyes = 3/9
phot = 2/9
pmildyes = 4/9

In [12]:
# humidity 
pd.crosstab(data["humidity"], data["play"], margins=True)

play      No  Yes  All
humidity
High       4    3    7
Normal     1    6    7
All        5    9   14

In [13]:
phighno = 4/5
pnormalno = 1/5

phighyes = 3/9
pnormalyes = 6/9

In [14]:
# wind
pd.crosstab(data["wind"], data["play"], margins=True)

play    No  Yes  All
wind
Strong   3    3    6
Weak     2    6    8
All      5    9   14

In [15]:
pstrongno = 2/5
pweakno = 2/5

pstrongyes = 3/9
pweakyes = 6/9

In [17]:
# outlook = sunny, temp = hot, humidity = high, wind = weak
Pyesc= py *psy *phot *phighyes *pweakyes
Pyesc

0.007054673721340388

In [18]:
Pno = psn * photno * phighno * pweakno * pn
Pno

0.02742857142857143

# NO PLAY  (PYES > PNO)