# Pandas Tutorial

Pandas is an open-source library that is built on top of NumPy library. It is a Python package that offers various data structures and operations for manipulating numerical data and time series. It is mainly popular for importing and analyzing data much easier. Pandas is fast and it has high-performance & productivity for users.

### Loading a CSV File

In [ ]:
# Load library
import pandas as pd
# Load dataset
dataframe = pd.read_csv('data.csv',delimiter=';')             # can also read text file
dataframe

     ID    name  age     Sex  Score1  Score2
0  cs20     Ram   25    Male      45      65
1  cs12   Sonia   26  Female      65      90
2  cs15    Ansh   22    Male      78      80
3  cs18   Vipin   26    Male      58      60
4  cs46  Anjali   24  Female      82      85
5  cs23  Anupma   23  Female      77      64

In [ ]:
# View first two rows
dataframe.head(2)

     ID   name  age     Sex  Score1  Score2
0  cs20    Ram   25    Male      45      65
1  cs12  Sonia   26  Female      65      90

In [ ]:
# View last two rows
dataframe.tail(2)

     ID    name  age     Sex  Score1  Score2
4  cs46  Anjali   24  Female      82      85
5  cs23  Anupma   23  Female      77      64

### Loading an Excel File

In [ ]:
# Load library
import pandas as pd
# Load data
dataframe = pd.read_excel('data1.xlsx')
# View the first two rows
dataframe.head(2)

  Name   Age      Sex  Score1  Score2
0     P    25    Male      45      65
1     Q    26  Female      65      90

### Creating a Data Frame

In [ ]:
# Load library
import pandas as pd
# Create DataFrame
dataframe = pd.DataFrame()
# Add columns
dataframe['Name'] = ['Jack', 'Steven ']
dataframe['Age'] = [38, 25]
dataframe['Driver'] = [True, False]
# Show DataFrame
dataframe

      Name  Age  Driver
0     Jack   38    True
1  Steven    25   False

Alternatively, once we have created a DataFrame object, we can append new rows to the bottom:

In [ ]:
# Create row
new_person = pd.Series(['Bob', 40, True], index=['Name','Age','Driver'])
# Append row
dataframe.append(new_person, ignore_index=True)

      Name  Age  Driver
0     Jack   38    True
1  Steven    25   False
2      Bob   40    True

### Describing the data

In [ ]:
# Show dimensions
dataframe.shape

(2, 3)

Additionally, we can get descriptive statistics for any **numeric columns** using
describe:

In [ ]:
# Show statistics
dataframe.describe()

             Age
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

### Navigating DataFrames

In [ ]:
# importing pandas as pd
import pandas as pd

# importing numpy as np
import numpy as np

# dictionary of lists
dict = {'Name':['A','B','C','D'],
        'Age':[25,22,28,22],
        'Sex':['Female','Male','Female','Male'],
        'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}

# creating a dataframe from dictionary
dataframe = pd.DataFrame(dict)
dataframe

  Name  Age     Sex  First Score  Second Score  Third Score
0    A   25  Female        100.0          30.0          NaN
1    B   22    Male         90.0          45.0         40.0
2    C   28  Female          NaN          56.0         80.0
3    D   22    Male         95.0           NaN         98.0

In [ ]:
# Select first row
dataframe.iloc[0]

Name                 A
Age                 25
Sex             Female
First Score        100
Second Score        30
Third Score        NaN
Name: 0, dtype: object

We can use `:` to define a slice of rows we want, such as selecting the second, third,
and fourth rows:

In [ ]:
# Select three rows
dataframe.iloc[1:4]

  Name  Age     Sex  First Score  Second Score  Third Score
1    B   22    Male         90.0          45.0         40.0
2    C   28  Female          NaN          56.0         80.0
3    D   22    Male         95.0           NaN         98.0

We can even use it to get all rows up to a point, such as **all rows up to and including the fourth row:**

In [ ]:
# Select three rows
dataframe.iloc[:4]

  Name  Age     Sex  First Score  Second Score  Third Score
0    A   25  Female        100.0          30.0          NaN
1    B   22    Male         90.0          45.0         40.0
2    C   28  Female          NaN          56.0         80.0
3    D   22    Male         95.0           NaN         98.0

In [ ]:
# second, third rows having all columns
dataframe.iloc[1:3, :]

  Name  Age     Sex  First Score  Second Score  Third Score
1    B   22    Male         90.0          45.0         40.0
2    C   28  Female          NaN          56.0         80.0

In [ ]:
# second, third rows with only Name and Age columns
dataframe.iloc[1:3, :2]

  Name  Age
1    B   22
2    C   28

DataFrames do not need to be numerically indexed.

In [ ]:
d7ataframe['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: object

DataFrames do not need to be numerically indexed. We can set the index of a Data‐
Frame to any value where the value is unique to each row.

In [ ]:
# Set index
dataframe = dataframe.set_index(dataframe['Name'])
# Show row
dataframe.loc['B']

Name               B
Age               22
Sex             Male
First Score       90
Second Score      45
Third Score       40
Name: B, dtype: object

### Selecting Rows Based on Conditionals

In [ ]:
# Show rows where column 'sex' is 'female'
dataframe[dataframe['Sex'] == 'Female']

     Name  Age     Sex  First Score  Second Score  Third Score
Name
A       A   25  Female        100.0          30.0          NaN
C       C   28  Female          NaN          56.0         80.0

Multiple conditions are easy as well.

In [ ]:
# Filter rows
dataframe[(dataframe['Sex'] == 'Female') & (dataframe['Age'] >= 27)]

     Name  Age     Sex  First Score  Second Score  Third Score
Name
C       C   28  Female          NaN          56.0         80.0

### Replacing Values

pandas’ replace is an easy way to find and replace values. For example, we can
replace any instance of "female" in the Sex column with "Woman":

In [ ]:
# Replace values, show two rows
dataframe['Sex'].replace("Female", "Woman")

Name
A    Woman
B     Male
C    Woman
D     Male
Name: Sex, dtype: object

We can also replace multiple values at the same time:

In [ ]:
# Replace "female" and "male with "Woman" and "Man"
dataframe['Sex'].replace(["Female", "Male"], ["Woman", "Man"])

Name
A    Woman
B      Man
C    Woman
D      Man
Name: Sex, dtype: object

### Finding the Minimum, Maximum, Sum, Average, and Count

In [ ]:
print('Maximum:', dataframe['Age'].max())
print('Minimum:', dataframe['Age'].min())
print('Mean:', dataframe['Age'].mean())
print('Sum:', dataframe['Age'].sum())
print('Count:', dataframe['Age'].count())

Maximum: 28
Minimum: 22
Mean: 24.25
Sum: 97
Count: 4

In [ ]:
# Show counts
dataframe.count()         # count non null values

Name            4
Age             4
Sex             4
First Score     3
Second Score    3
Third Score     3
dtype: int64

### Finding Unique Values

In [ ]:
# Select unique values
dataframe['Sex'].unique()

array(['Female', 'Male'], dtype=object)

Alternatively, value_counts will display all unique values with the number of times
each value appears:

In [ ]:
# Show counts
dataframe['Sex'].value_counts()

Female    2
Male      2
Name: Sex, dtype: int64

In [ ]:
# Show counts
dataframe['Age'].value_counts()

22    2
25    1
28    1
Name: Age, dtype: int64

Finally, if we simply want to count the number of unique values, we can use nunique:

In [ ]:
# Show number of unique values
dataframe['Age'].nunique()

3

###  Deleting a Column

The best way to delete a column is to use drop with the parameter axis=1 (i.e., the
column axis):

In [ ]:
# Delete column
dataframe.drop('Age', axis=1).head(2)

     Name     Sex  First Score  Second Score  Third Score
Name
A       A  Female        100.0          30.0          NaN
B       B    Male         90.0          45.0         40.0

You can also use a list of column names as the main argument to drop multiple columns
at once:

In [ ]:
# Drop columns
dataframe.drop(['Age', 'Sex'], axis=1).head(2)

     Name  First Score  Second Score  Third Score
Name
A       A        100.0          30.0          NaN
B       B         90.0          45.0         40.0

If a column does not have a name (which can sometimes happen), you can drop it by
its column index using dataframe.columns:

In [ ]:
# Drop column
dataframe.drop(dataframe.columns[1], axis=1).head(2)

     Name     Sex  First Score  Second Score  Third Score
Name
A       A  Female        100.0          30.0          NaN
B       B    Male         90.0          45.0         40.0

### Deleting a Row

In [ ]:
# Delete rows
dataframe[dataframe['Sex'] != 'Male'].head(2)

     Name  Age     Sex  First Score  Second Score  Third Score
Name
A       A   25  Female        100.0          30.0          NaN
C       C   28  Female          NaN          56.0         80.0

### Dropping Duplicate Rows

In [ ]:
# Drop duplicates , here no rows are duplicate
dataframe.drop_duplicates()

     Name  Age     Sex  First Score  Second Score  Third Score
Name
A       A   25  Female        100.0          30.0          NaN
B       B   22    Male         90.0          45.0         40.0
C       C   28  Female          NaN          56.0         80.0
D       D   22    Male         95.0           NaN         98.0

### Looping Over a Column

In [ ]:
# Print first two names uppercased
for name in dataframe['Sex'][0:2]:      # [0:2] only first two
    print(name.upper())

FEMALE
MALE

### Concatenating DataFrames

Use concat with axis=0 to concatenate along the row axis:

In [ ]:
# Load library
import pandas as pd
# Create DataFrame
data_a = {'id': ['1', '2', '3'],
'first': ['Alex', 'Amy', 'Allen'],
'last': ['Anderson', 'Ackerman', 'Ali']}
dataframe_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])
# Create DataFrame
data_b = {'id': ['4', '5', '6'],
'first': ['Billy', 'Brian', 'Bran'],
'last': ['Bonder', 'Black', 'Balwner']}
dataframe_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])
# Concatenate DataFrames by rows
pd.concat([dataframe_a, dataframe_b], axis=0)

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

You can use axis=1 to concatenate along the column axis:

In [ ]:
# Concatenate DataFrames by columns
pd.concat([dataframe_a, dataframe_b], axis=1)

  id  first      last id  first     last
0  1   Alex  Anderson  4  Billy   Bonder
1  2    Amy  Ackerman  5  Brian    Black
2  3  Allen       Ali  6   Bran  Balwner

### Removing Duplicates

In [ ]:
# dictionary of lists
dict = {'K1':['One']*3+['two']*4,
        'K2':[1,1,2,3,3,4,4]}

# creating a dataframe from dictionary
df = pd.DataFrame(dict)
df

    K1  K2
0  One   1
1  One   1
2  One   2
3  two   3
4  two   3
5  two   4
6  two   4

In [ ]:
df.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [ ]:
df.drop_duplicates()

    K1  K2
0  One   1
2  One   2
3  two   3
5  two   4